version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: uncle_db
    environment:
      POSTGRES_USER: uncle
      POSTGRES_PASSWORD: verystrongpassword
      POSTGRES_DB: uncledb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
