ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 8080
db:
#    driverClassName: "org.postgresql.Driver"
  jdbcURL: "jdbc:postgresql://localhost:5432/uncledb"
  user: "uncle"
  password: "verystrongpassword"
